name: checks

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      GAS: true
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v4
          with:
            go-version-file: 'go.mod'
        - run: go version
        - name: Run check
          run: go run main.go
